declare namespace Cloudflare {
  interface Env {
    DB: D1Database;
    ALIBABA_CLOUD_ACCESS_KEY_ID?: string;
    ALIBABA_CLOUD_ACCESS_KEY_SECRET?: string;
    ALIBABA_CLOUD_SECURITY_TOKEN?: string;
    PULSEDNS_SELF_HOSTED?: string;
    PULSEDNS_DB_PATH?: string;
    PULSEDNS_PUBLIC_URL?: string;
    PULSEDNS_BASE_PATH?: string;
    NEXT_PUBLIC_PULSEDNS_BASE_PATH?: string;
    PULSEDNS_PANEL_PORT?: string;
    PULSEDNS_ADMIN_USER?: string;
    PULSEDNS_ADMIN_PASSWORD?: string;
    PULSEDNS_ADMIN_EMAIL?: string;
    PULSEDNS_TASK_ENCRYPTION_KEY?: string;
    PULSEDNS_NYANPASS_INSTALLER_URL?: string;
    PULSEDNS_NYANPASS_INSTALLER_SHA256?: string;
    PULSEDNS_NYANPASS_BINARY_BASE_URL?: string;
    PULSEDNS_NYANPASS_BINARY_RELEASE?: string;
    PULSEDNS_NYANPASS_BINARY_AMD64_SHA256?: string;
    PULSEDNS_NYANPASS_BINARY_AMD64V3_SHA256?: string;
    PULSEDNS_NYANPASS_BINARY_ARM64_SHA256?: string;
  }
}
